---
apiVersion: skaffold/v2beta23
kind: Config
build:
  artifacts:
    - image: retroachievements
      context: ./..
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - "kube/*"
